#!/usr/bin/env python
# -*- coding: utf-8 -*-

STAR_NAMES = [
    "Canopus",
    "Dabih",
    "Suhail",
    "Asterion",
    "Kapteyn, Estrella de",
    "Azaleh",
    "Deneb Kaitos",
    "Kaus Medius",
    "Thuban",
    "Syrma",
    "Tseen Kee",
    "Regulus",
    "Deneb Kaitos Schemali",
    "Rijl al Awwa",
    "Markab",
    "Alterf",
    "Asellus Borealis",
    "Terebellum",
    "Lalande 21185",
    "Scheat",
    "Nair Al Saif",
    "WNC4",
    "Al Kalb al Rai",
    "Nashira",
    "Misam",
    "Zaniah",
    "Shaula",
    "Atlas",
    "Sadalmelik",
    "Subra",
    "Némesis",
    "Kappa Velorum",
    "Sadr",
    "Adhara",
    "Ksora",
    "Azelfafage",
    "Kaus Australis",
    "Nunki",
    "Algenib",
    "S Andromedae",
    "Betria",
    "Scheddi",
    "Altair",
    "Marfik",
    "Muliphein",
    "Cebalrai",
    "Giennah",
    "Maia",
    "Chertan",
    "Menkib",
    "Menkalinan",
    "Hadir",
    "Alnitak",
    "Minchir",
    "Hyadum II",
    "Situla",
    "BPM 37093",
    "Rigil Kentaurus",
    "Sarin",
    "R Hydrae",
    "Talitha Borealis",
    "Sham",
    "Schedir",
    "Sadalsuud",
    "Sabik",
    "Alcyone",
    "Acubens",
    "Unuk",
    "Praecipua",
    "Tania Borealis",
    "Wezen",
    "Kraz",
    "Merope",
    "R Leonis",
    "Deneb",
    "Altarf",
    "Chi Cygni",
    "Tania Australis",
    "Barnard, Estrella de",
    "Girtab",
    "Aldebarán",
    "Alya",
    "Nash",
    "Ross 248",
    "Mintaka",
    "La Superba",
    "Chow",
    "Polaris Australis",
    "Alathfar",
    "Betelgeuse",
    "Acrux",
    "Arcturus",
    "Edasich",
    "Keid",
    "Benetnasch",
    "Chara",
    "Alnilam",
    "Tabit",
    "Nekkar",
    "Beid",
    "Sualocin",
    "Homam",
    "Angetenar",
    "Alrischa",
    "Kajam",
    "Alamak",
    "Tegmen",
    "Alcor",
    "Asellus Tertius",
    "Asellus Australis",
    "Alrakis",
    "Kornephoros",
    "Dheneb",
    "Sirius",
    "Gatria",
    "Miram",
    "Errai",
    "Minelava",
    "Deneb el Okab",
    "Al Giedi",
    "Alphecca",
    "Alula Australis",
    "Baten Kaitos",
    "Nihal",
    "Spica",
    "Ruchba",
    "Rotanev",
    "Póllux",
    "Alioth",
    "Al Niyat",
    "Caph",
    "Avior",
    "Arneb",
    "Kaffaljidhma",
    "Mufrid",
    "Cygnus X-1",
    "Murzim",
    "Grafías",
    "Azmidiske",
    "Alschain",
    "Gianfar",
    "Aspidiske",
    "Theemin",
    "Alpha Centauri",
    "Capella",
    "Albali",
    "Algorab",
    "Heka",
    "Zubeneschamali",
    "Pleione",
    "Mirfak",
    "Diadem",
    "Sulafat",
    "Phecda",
    "Regor",
    "Alsafi",
    "Menkent",
    "Hyadum I",
    "Asellus Primus",
    "Azha",
    "Aldhafera",
    "SN 1006",
    "Kruger 60",
    "Zaurak",
    "Torcularis Septemtrionalis",
    "Kitalpha",
    "Kaus Borealis",
    "Seat",
    "Muscida",
    "Alshat",
    "Decrux",
    "Aldhibain",
    "Aludra",
    "Tejat Posterior",
    "Elnath",
    "Achird",
    "Jabbah",
    "Albireo",
    "Brachium",
    "Deneb Dulfim",
    "Zavijava",
    "SN 1572",
    "Deneb Algedi",
    "Kuma",
    "Lesath",
    "Matar",
    "Thabit",
    "Askella",
    "Mizar",
    "Izar",
    "Albaldah",
    "Botein",
    "Tarazed",
    "Achernar",
    "Kochab",
    "Polaris",
    "Fum al Samakah",
    "Alkes",
    "Becrux",
    "Ancha",
    "Alkalurops",
    "Saiph",
    "Cástor",
    "Sheliak",
    "Tureis",
    "Gorgonea Tertia",
    "Atria",
    "Rana",
    "Wolf 359",
    "Marfark",
    "Wei",
    "Menchib",
    "Alderamin",
    "Cursa",
    "Menkar",
    "Elmuthalleth",
    "Sceptrum",
    "Hassaleh",
    "Skat",
    "Tien Kuan",
    "Mira",
    "Zubenelgenubi",
    "Enif",
    "Ras Alhague",
    "Aladfar",
    "Pherkad",
    "Arkab Prior",
    "Alchiba",
    "Asterope",
    "Adid Australis",
    "Bharani",
    "Phact",
    "Hamal",
    "Acrab",
    "Navi",
    "Giedi",
    "Head of Hydrus",
    "Gomeisa",
    "Lucida Anseris",
    "M40",
    "Sterope II",
    "Atik",
    "Arrakis",
    "Bellatrix",
    "Taygeta",
    "Sol",
    "Fomalhaut",
    "Ross 154",
    "Ras Algethi",
    "Alfirk",
    "Sheratan",
    "Maasym",
    "Yed Prior",
    "Etamin",
    "Procyon",
    "Próxima Centauri",
    "Rasalas",
    "Lacaille 9352",
    "Tyl",
    "Wazn",
    "Garnet Star",
    "Al Minliar al Asad",
    "Altais",
    "P Cygni",
    "Zuben-el-Akribi",
    "Acamar",
    "Naos",
    "Heze",
    "Alzir",
    "Merga",
    "SN 1054",
    "Alkurah",
    "LBV 1806-20",
    "Rukbat",
    "Pistol Star",
    "Denébola",
    "Aldhanab",
    "Gienah Gurab",
    "Mekbuda",
    "Toliman",
    "Mebsuta",
    "Merak",
    "Mesarthim",
    "Beta Gruis",
    "Gacrux",
    "Asellus Secundus",
    "Sadalbari",
    "Celaeno",
    "Grumium",
    "Seginus",
    "Mothallah",
    "SN 1604",
    "Wasat",
    "Rigel",
    "Alfecca Meridiana",
    "Furud",
    "Algieba",
    "Tejat Prior",
    "Pherkard",
    "Mu Arae",
    "Electra",
    "Al Nair",
    "Duhr",
    "SN 1181",
    "Aldhibah",
    "Alwaid",
    "Dschubba",
    "Nusakan",
    "Ain",
    "Haldus",
    "Dubhe",
    "Vega",
    "Ras Elased Australis",
    "Arkab Posterior",
    "Porrima",
    "Ross 128",
    "Antares",
    "Hadar",
    "Bunda",
    "Yed Posterior",
    "Zuben-el-Akrab",
    "Peacock",
    "Megrez",
    "Mirach",
    "Alniyat",
    "Vindemiatrix",
    "Minkar",
    "Miaplacidus",
    "Baham",
    "Sadachbia",
    "Kullat Nunu",
    "Alhena",
    "Algol",
    "Alula Borealis",
    "Talitha Australis",
    "Segin",
]
